Repository MYCIN-AI-Club/ML-Guide, pull requests merged in 2022-10, with the labels that each got.

#20 Add Python_Data _Structures
  Python_Data_Structures.ipynb
Labels: enhancement, hacktoberfest-accepted

#19 Update ML_BEGINNERGUIDE.ipynb
  ML_BEGINNERGUIDE.ipynb
Labels: hacktoberfest-accepted

#22 Add files via upload
  python_functions.ipynb
Labels: hacktoberfest-accepted

#30 Added placement-prediction
  placement-prediction
Labels: good first issue, hacktoberfest-accepted

#32 node js
  node
Labels: good first issue, hacktoberfest-accepted

#31 Added disease predicition
  exx.py
Labels: hacktoberfest-accepted

#29 Create Some_sorting_techniques_in_python.ipynb
  Some_sorting_techniques_in_python.ipynb
Labels: hacktoberfest-accepted

#35 project on ml
  pr2
Labels: hacktoberfest-accepted

#28 Created Python_Function
  Python Functions.docx
Labels: hacktoberfest-accepted

#36 .
  Classification Model to Identify Species of IRIS Flower Solution.ipynb
Labels: hacktoberfest-accepted

#38 Python_Function
  Python_Functions.py
Labels: hacktoberfest-accepted

#37 Created using Colaboratory
  ML_linear_reg.ipynb
Labels: hacktoberfest-accepted
